// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTSywCd0J5gOmOEQZ5mgR27SDHhuNbXlE',
    appId: '1:1048174520725:web:a01833609d489c06732e9c',
    messagingSenderId: '1048174520725',
    projectId: 'basictest-34ed3',
    authDomain: 'basictest-34ed3.firebaseapp.com',
    databaseURL: 'https://basictest-34ed3-default-rtdb.firebaseio.com',
    storageBucket: 'basictest-34ed3.firebasestorage.app',
    measurementId: 'G-C35Q7ZY5DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrYDn44A5DbspUjbObieC00JG07HtKLjo',
    appId: '1:1048174520725:android:9eb012bb146937e9732e9c',
    messagingSenderId: '1048174520725',
    projectId: 'basictest-34ed3',
    databaseURL: 'https://basictest-34ed3-default-rtdb.firebaseio.com',
    storageBucket: 'basictest-34ed3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAu-aCPjHo6vuFN7Qf9oOUJot3A2qoOB8',
    appId: '1:1048174520725:ios:63c5948dc5b3227b732e9c',
    messagingSenderId: '1048174520725',
    projectId: 'basictest-34ed3',
    databaseURL: 'https://basictest-34ed3-default-rtdb.firebaseio.com',
    storageBucket: 'basictest-34ed3.firebasestorage.app',
    androidClientId: '1048174520725-o4n3dvbp5go3tnd29s4buqhub86kfvgu.apps.googleusercontent.com',
    iosClientId: '1048174520725-v9t5enlltnad1cepjb7tlpnfnfsd9p85.apps.googleusercontent.com',
    iosBundleId: 'com.example.gaplog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAu-aCPjHo6vuFN7Qf9oOUJot3A2qoOB8',
    appId: '1:1048174520725:ios:63c5948dc5b3227b732e9c',
    messagingSenderId: '1048174520725',
    projectId: 'basictest-34ed3',
    databaseURL: 'https://basictest-34ed3-default-rtdb.firebaseio.com',
    storageBucket: 'basictest-34ed3.firebasestorage.app',
    androidClientId: '1048174520725-o4n3dvbp5go3tnd29s4buqhub86kfvgu.apps.googleusercontent.com',
    iosClientId: '1048174520725-v9t5enlltnad1cepjb7tlpnfnfsd9p85.apps.googleusercontent.com',
    iosBundleId: 'com.example.gaplog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTSywCd0J5gOmOEQZ5mgR27SDHhuNbXlE',
    appId: '1:1048174520725:web:ca18c9842f2f6b2d732e9c',
    messagingSenderId: '1048174520725',
    projectId: 'basictest-34ed3',
    authDomain: 'basictest-34ed3.firebaseapp.com',
    databaseURL: 'https://basictest-34ed3-default-rtdb.firebaseio.com',
    storageBucket: 'basictest-34ed3.firebasestorage.app',
    measurementId: 'G-4PMPBL8B6J',
  );
}
